; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32 @6.5.0
board = lilygo_t_cameraplus_esp32s3
framework = arduino
monitor_speed = 115200 ;Serial Baud Rate Setting

; debug_tool = esp-builtin
; upload_protocol = esp-builtin
upload_speed = 921600 ; 460800, 512000, 460800, 256000, 115200
board_upload.flash_size = 16MB 

; board_build.memory_type = qio_opi ;Enable internal PSRAM
board_build.memory_type = qio_qspi ;Enable external PSRAM

board_build.partitions = default_16MB.csv 

build_flags = 
    -Wall ;all errors that everybody could agree on
    -Wextra ;somebody agree on
    ; -Werror ;Think of "Warning" as "Error".
    -D CORE_DEBUG_LEVEL=2 ;Debug level 0-5
    -D BOARD_HAS_PSRAM ;Enable external PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1 ;1 is to use the USB port as a serial port
    -D ARDUINO_RUNNING_CORE=1       ; Arduino Runs On Core (setup, loop)
    -D ARDUINO_EVENT_RUNNING_CORE=1 ; Events Run On Core

[platformio]
boards_dir = ./boards
lib_dir = ./libraries

src_dir = examples/${platformio.default_envs}
; default_envs = Wifi_Scan
; default_envs = Wifi_Music
; default_envs = SD_Music
; default_envs = DMIC_ReadData
; default_envs = SD_DMIC
; default_envs = TFT
; default_envs = IIC_Scan_2
; default_envs = Camera_WebServer
; default_envs = CST816D
; default_envs = GFX_Test
; default_envs = SY6970
; default_envs = SD_MJPEG
; default_envs = SD_MJPEG_Mp3
; default_envs = Lvgl_UI
; default_envs = Camera_Screen
default_envs = Camera_WebServer_OV5640_Auto_Focus
; default_envs = Camera_Screen_OV5640_Auto_Focus

; src_dir = debug/examples/${platformio.default_envs}
; default_envs = IO
; default_envs = Wifi_AP
; default_envs = SD
; default_envs = INT_Test
; default_envs = IIC_Scan
; default_envs = Uart
; default_envs = Chip_Scan
; default_envs = SD_Music_2
; default_envs = Lvgl_Ciallo
; default_envs = Dual_Core_CPU
; default_envs = SD_Explorer
; default_envs = Lvgl_Explorer
; default_envs = Lvgl_Music
; default_envs = CST816D_2
; default_envs = IIC_Drive
; default_envs = Wifi_STA
; default_envs = Deep_Sleep_Wake_Up
; default_envs = Light_Sleep_Wake_Up
; default_envs = SY6970_2
; default_envs = DMIC_ReadData_2
; default_envs = DMIC_SD
; default_envs = WIFI_HTTP_Download_File
; default_envs = OV5640_Console_Test

[env:Wifi_Scan]
[env:Wifi_Music]
[env:SD_Music]
[env:DMIC_ReadData]
[env:SD_DMIC]
[env:TFT]
[env:IIC_Scan_2]
[env:Camera_WebServer]
[env:CST816D]
[env:GFX_Test]
[env:SY6970]
[env:SD_MJPEG]
[env:SD_MJPEG_Mp3]
[env:Lvgl_UI]
build_flags = 
        -D LV_LVGL_H_INCLUDE_SIMPLE
        -D LV_USE_DCLOCK ;Using lvgl DCLOCK components
        -D LV_USE_CAROUSEL
[env:Camera_Screen]
[env:Camera_WebServer_OV5640_Auto_Focus]
[env:Camera_Screen_OV5640_Auto_Focus]

[env:IO]
[env:Wifi_AP]
[env:SD]
[env:INT_Test]
[env:IIC_Scan]
[env:Uart]
[env:Chip_Scan]
[env:Lvgl_Ciallo]
[env:SD_Music_2]
[env:Dual_Core_CPU]
[env:SD_Explorer]
[env:Lvgl_Explorer]
build_flags = 
        -D LV_LVGL_H_INCLUDE_SIMPLE
        -D LV_USE_DCLOCK ;Using lvgl DCLOCK components
        -D LV_USE_CAROUSEL
[env:Lvgl_Music]
build_flags = 
        -D LV_LVGL_H_INCLUDE_SIMPLE
        -D LV_USE_DCLOCK ;Using lvgl DCLOCK components
        -D LV_USE_CAROUSEL
[env:CST816D_2]
[env:IIC_Drive]
[env:Wifi_STA]
[env:Deep_Sleep_Wake_Up]
[env:Light_Sleep_Wake_Up]
[env:SY6970_2]
[env:DMIC_ReadData_2]
[env:DMIC_SD]
[env:WIFI_HTTP_Download_File]
[env:OV5640_Console_Test]


